steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg=VITE_ENVIRONMENT=${_VITE_ENVIRONMENT}"
      - "--build-arg=VITE_SUPABASE_URL=${_VITE_SUPABASE_URL}"
      - "--build-arg=VITE_SUPABASE_PUBLISHABLE_KEY=${_VITE_SUPABASE_PUBLISHABLE_KEY}"
      - "--build-arg=VITE_API_BASE_URL=${_VITE_API_BASE_URL}"
      - "-t"
      - "gcr.io/$PROJECT_ID/frontend:$SHORT_SHA"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/frontend:$SHORT_SHA"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - "run"
      - "deploy"
      - "frontend"
      - "--image=gcr.io/$PROJECT_ID/frontend:$SHORT_SHA"
      - "--region=us-central1"
      - "--platform=managed"

images:
  - "gcr.io/$PROJECT_ID/frontend:$SHORT_SHA"
