name: Backend Build Check

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -f backend/Dockerfile ./backend
